-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.7.24 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping data for table ionicapiplaces.places: ~14 rows (approximately)
/*!40000 ALTER TABLE `places` DISABLE KEYS */;
INSERT INTO `places` (`id`, `title`, `description`, `imageUrl`, `latitude`, `logitude`, `category`, `created_at`, `updated_at`) VALUES
	(1, 'Royal Malaysia Police Museum 1', 'The Royal Malaysia Police Museum (Malay: Muzium Polis Diraja Malaysia) is a museum that showcases the history of the Malaysia police force, located in Kuala Lumpur, Malaysia. The museum includes exhibits from the history of the Royal Malaysia Police since its origins under British colonial rule until the 1970s. It is open daily, except Monday, from 1000 to 1800 hours, and admission is free.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Royal_Malaysian_Police_Museum.JPG/400px-Royal_Malaysian_Police_Museum.JPG', '3.140923', '101.688709', 'Museum', NULL, '2020-12-03 23:16:28'),
	(2, 'Perdana Botanical Gardens', 'Perdana Botanical Gardens, formerly Perdana Lake Gardens, Lake Gardens and Public Gardens, is Kuala Lumpur\'s first large-scale recreational park. Measuring 91.6 hectares, it is located in the heart of the city and established in 1888. The park served as place of refuge from the hustle and bustle of the city during colonial times. It contains large sculpted and manicured gardens and a host of attractions.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Kuala_Lumpur_Perdana_Lake_Garden_01.jpg/400px-Kuala_Lumpur_Perdana_Lake_Garden_01.jpg', '2.982293', '101.528389', 'Park', NULL, NULL),
	(3, 'Islamic Arts Museum Malaysia', '"The Islamic Arts Museum Malaysia (Malay: Muzium Kesenian Islam Malaysia) was officially opened on 12 December 1998. The museum is located in the heart of Kuala Lumpur’s tourist belt amidst the lush greenery of Perdana Botanical Gardens and within walking distance to the National Mosque, Bird Park and National Planetarium.\r\n\r\nThe museum is the largest museum of Islamic arts in South East Asia with more than seven thousands artifacts from the Islamic world."', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Muzium_Kesenian_Islam_Malaysia_7.jpg/293px-Muzium_Kesenian_Islam_Malaysia_7.jpg', '3.119291', '101.689018', 'Museum', NULL, NULL),
	(4, 'Kuala Lumpur Bird', 'A gated attraction, Kuala Lumpur Bird Park (Malay: Taman Burung Kuala Lumpur) is a 20.9-acre (8.5 ha) public aviary in Kuala Lumpur, Malaysia. It is a popular tourist attraction in the country, receiving an annual average of 200,000 visitors. It is located adjacent to the Lake Gardens within a KL green lung in Bukit Aman, close to the National Mosque and Royal Malaysian Police Museum. The Bird Park houses more than 3,000 birds representing more than 200 species in an enclosed aviary. About 90% are local birds and 10% were imported from countries such as Australia, China, Holland, Indonesia, New Guinea, Tanzania and Thailand.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/KL_Bird_park_net.jpg/400px-KL_Bird_park_net.jpg', '3.119291', '101.689018', 'Zoo', NULL, '2020-12-03 19:44:13'),
	(5, 'Kuala Lumpur Bird Park', 'A gated attraction, Kuala Lumpur Bird Park (Malay: Taman Burung Kuala Lumpur) is a 20.9-acre (8.5 ha) public aviary in Kuala Lumpur, Malaysia. It is a popular tourist attraction in the country, receiving an annual average of 200,000 visitors. It is located adjacent to the Lake Gardens within a KL green lung in Bukit Aman, close to the National Mosque and Royal Malaysian Police Museum. The Bird Park houses more than 3,000 birds representing more than 200 species in an enclosed aviary. About 90% are local birds and 10% were imported from countries such as Australia, China, Holland, Indonesia, New Guinea, Tanzania and Thailand.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/KL_Bird_park_net.jpg/400px-KL_Bird_park_net.jpg', '3.119291', '101.689018', 'Zoo', NULL, NULL),
	(6, 'Muzium Negara', 'The National Museum (Malay: Muzium Negara) is a museum located on Jalan Damansara in Kuala Lumpur, Malaysia. The museum is situated in close proximity to the Perdana Lake Gardens and it provides an overview of Malaysian history and culture. The National Museum is a palatial structure built in the style of Rumah Gadang, an aspect of Minangkabau architecture. Its facade comprises elements of traditional Malay and modern features. It was opened on 31 August 1963, and it serves as a repository of Malaysia\'s rich cultural and historical heritage.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/National_museum%2C_KL.JPG/400px-National_museum%2C_KL.JPG', '3.119291', '101.689018', 'National museum', NULL, NULL),
	(7, 'Malay World Gallery', 'Muzium Etnologi Dunia Melayu mempamerkan koleksi dan penyelidikan mengenai dunia Melayu. Pameran koleksi meliputi pelbagai jenis seperti tekstil, senjata, ukiran, alat logam dan teknologi, perhiasan diri, alat muzik dan sebagainya. Koleksi-koleksi ini termasuk dari beberapa buah negara seperti Malaysia, Indonesia, Thailand, Filipina, Kemboja, Vietnam, Afrika Selatan, Madagaskar dan lain-lain negara seluruh dunia termasuk rumpun Melayu Polenesia.', 'https://4.bp.blogspot.com/-ulCOzQs75NQ/WaLis3sC7vI/AAAAAAAAAoA/SYVxEFk51qc295tqN4a4Z5rPXU27AmAUACLcBGAs/s1600/2.jpg', '3.119291', '101.689018', 'Museum', NULL, NULL),
	(8, 'Makam Pahlawan 1', 'The Makam Pahlawan (Malay for Heroes\' Mausoleum) is the burial ground of several Malaysian leaders and politicians. It is located near the Malaysian national mosque, Masjid Negara in the national capital, Kuala Lumpur. Construction of the mausoleum began in 1963 under its project of the construction of Masjid Negara and was completed in 1965.', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/KualaLumpurMakamPahlawan.jpg/400px-KualaLumpurMakamPahlawan.jpg', '3.119291', '101.689018', 'Cemetery, Mausoleum', NULL, '2020-12-04 01:12:22'),
	(9, 'Kuala Lumpur Butterfly Park', '"Kuala Lumpur Butterfly Park (Malay: Taman Rama Rama Kuala Lumpur) is a large public butterfly zoo in Kuala Lumpur, Malaysia. It is a popular tourist attraction in the country. It is located adjacent to the Lake Gardens and Kuala Lumpur Bird Park. The butterfly park houses many species that are local to the country.\r\n\r\nSpanning over 80,000 square feet of landscaped garden with over 5,000 butterflies, exotic plants, butterfly-host plants and ferns, it is one of the largest houses in the world. The park also houses an exhibition area with information on butterflies and other insects, and offers a souvenir store for tourists at the end of the tour."', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Kuala_Lumpur_Butterfly_Park_%285%29.jpg/400px-Kuala_Lumpur_Butterfly_Park_%285%29.jpg', '3.119291', '101.689018', 'Zoo', NULL, NULL),
	(10, 'National Mosque', 'The National Mosque of Malaysia (Malay: Masjid Negara Malaysia) is a mosque in Kuala Lumpur, Malaysia. It has a capacity for 15,000 people and is situated among 13 acres (53,000 m2) of gardens. The original structure was designed by a three-person team from the Public Works Department: UK architect Howard Ashley, and Malaysians Hisham Albakri and Baharuddin Kassim. The engineer in charge of the construction of the mosque, which commenced in 1963 was Antony Morris. It was built on the site of a church, the Venning Road Brethren Gospel Hall, which had stood there since 1922 but was appropriated by the Malaysian government. The mosque is a bold and modern approach in reinforced concrete, symbolic of the aspirations of a then newly independent Malaysia.', 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Malaysia_Masjid_Negara.jpg', '3.119291', '101.689018', 'Mosque', NULL, NULL),
	(11, 'Wei-Ling Gallery', 'Wei Ling Gallery is an art gallery located in Kuala Lumpur, Malaysia in the Brickfields area. The gallery was founded by Lim Wei-Ling in 2002 to actively encourage the works of Malaysian contemporary artists and Malaysian culture. The gallery\'s collection offers an overview of modern and contemporary art, including works of architecture and design, drawing, painting, sculpture, photography, prints, electronic media and artist\'s books.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Wei-Ling_Gallery_Brickfields_%28_Interior_%29.png/400px-Wei-Ling_Gallery_Brickfields_%28_Interior_%29.png', '3.119291', '101.689018', 'Art gallery', NULL, NULL),
	(12, 'National Monument', '"The National Monument is a sculpture that commemorates those who died in Malaysia\'s struggle for freedom, principally against the Japanese occupation during World War II and the Malayan Emergency, which lasted from 1948 until 1960. It is located in the Federal capital, Kuala Lumpur. The Malaysian Houses of Parliament are situated near the monument.\r\n\r\nIt is the world\'s tallest bronze freestanding sculpture grouping. Every year on 31 July on Warriors\' Day, the Yang di-Pertuan Agong, the Prime Minister, heads of military, and the police pay their respects to the fallen heroes by laying garlands at the monument."', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kuala_Lumpur_Malaysia_Tugu-Negara-Malaysia-03.jpg/400px-Kuala_Lumpur_Malaysia_Tugu-Negara-Malaysia-03.jpg', '3.119291', '101.689018', 'Monument', NULL, NULL),
	(13, 'Dayabumi Complex', 'The Dayabumi Complex (Malay: Kompleks Dayabumi) is a major landmark in Kuala Lumpur, Malaysia. It houses several commercial facilities and is one of the earliest skyscrapers in the city.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Dayabumi%2C_Kuala_Lumpur_%28February_2007%29.jpg/294px-Dayabumi%2C_Kuala_Lumpur_%28February_2007%29.jpg', '3.119291', '101.689018', 'Skyscraper', NULL, NULL),
	(14, 'Kelana Jaya Line', 'The LRT Kelana Jaya line is the fifth rail transit line and the first fully automated and driverless rail system in the Klang Valley area and forms a part of the Greater KL/Klang Valley Integrated Transit System. Servicing 37 stations, the line has 46.4 km of grade-separated tracks running mostly on underground and elevated guideways. Formerly known as the PUTRA LRT, it is currently operated by Rapid Rail, a subsidiary of Prasarana Malaysia. It is named after its former terminus, Kelana Jaya station. The line is numbered   5  and coloured Ruby on the official transit map.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Yosri042005PuteraLRT.JPG/400px-Yosri042005PuteraLRT.JPG', '3.119291', '101.689018', 'Viaduct', NULL, NULL);
/*!40000 ALTER TABLE `places` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
